name: unpub_aws
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  unpub: ^2.0.0
  minio: ^3.0.0
  http: ^0.13.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.12
  chunked_stream: ^1.4.1
  mockito: ^5.0.16
  build_runner: ^2.1.2
  path: ^1.8.0
  json_annotation: ^4.1.0

dependency_overrides:
  unpub:
    path: ../unpub
